player1 = "Black or White"
player2 = "White or Black"
pieces = [["___","___","___","___","___","___","___"],["___","___","___","___","___","___","___"],["___","___","___","___","___","___","___"],["___","___","___","___","___","___","___"],["___","___","___","___","___","___","___"],["___","___","___","___","___","___","___"],["___","___","___","___","___","___","___"]]
print((pieces[0][0]),end=" ")
print((pieces[0][1]),end=" ")
print((pieces[0][2]),end=" ")
print((pieces[0][3]),end=" ")
print((pieces[0][4]),end=" ")
print((pieces[0][5]),end=" ")
print((pieces[0][6]),end=" ")
print()
print((pieces[1][0]),end=" ")
print((pieces[1][1]),end=" ")
print((pieces[1][2]),end=" ")
print((pieces[1][3]),end=" ")
print((pieces[1][4]),end=" ")
print((pieces[1][5]),end=" ")
print((pieces[1][6]),end=" ")
print()
print((pieces[2][0]),end=" ")
print((pieces[2][1]),end=" ")
print((pieces[2][2]),end=" ")
print((pieces[2][3]),end=" ")
print((pieces[2][4]),end=" ")
print((pieces[2][5]),end=" ")
print((pieces[2][6]),end=" ")
print()
print((pieces[3][0]),end=" ")
print((pieces[3][1]),end=" ")
print((pieces[3][2]),end=" ")
print((pieces[3][3]),end=" ")
print((pieces[3][4]),end=" ")
print((pieces[3][5]),end=" ")
print((pieces[3][6]),end=" ")
print()
print((pieces[4][0]),end=" ")
print((pieces[4][1]),end=" ")
print((pieces[4][2]),end=" ")
print((pieces[4][3]),end=" ")
print((pieces[4][4]),end=" ")
print((pieces[4][5]),end=" ")
print((pieces[4][6]),end=" ")
print()
print((pieces[5][0]),end=" ")
print((pieces[5][1]),end=" ")
print((pieces[5][2]),end=" ")
print((pieces[5][3]),end=" ")
print((pieces[5][4]),end=" ")
print((pieces[5][5]),end=" ")
print((pieces[5][6]),end=" ")
print()
print((pieces[6][0]),end=" ")
print((pieces[6][1]),end=" ")
print((pieces[6][2]),end=" ")
print((pieces[6][3]),end=" ")
print((pieces[6][4]),end=" ")
print((pieces[6][5]),end=" ")
print((pieces[6][6]),end=" ")
print()
print("INSTRUCTIONS:") 
print("This is a game of Tic-tac-Toe.  Here you must enter your coordinates for where your pieces are.")  
print("For the column, it is column 0, 1, 2, 3, 4, 5, and 6.")  
print("So for instance, if I were to enter the first column, I would say Column 0")
piece_chosen = input("Player 1: Black or White?")
if(piece_chosen == "Black"):
    print("OK.  You are controlling pieces Black")
    print("Player 2: You are controlling pieces White")
if(piece_chosen == "White"):
    print("OK.  You are controlling pieces White")
    print("Player 2: you are controlling pieces Black")
while(True):